resized_image_size: 128
device: "auto"
compute_cfg:
  device: auto
  num_workers: 4
data_cfg:
  train_ratio: 0.8
  truncate: 0.05
  resized_image_size: 128
trainer_cfg:
  batch_size: 8
  timesteps: 300
  n_embed: 32
  max_epochs: 64
  checkpoint_interval: 25
  loss_estimation_context: 10
  snapshot_path: "test-model-weights.pth"
  load_weights: False
optimizer_cfg:
  weight_decay: 0.1
  learning_rate: 0.001