compute_cfg:
  device: auto
  num_workers: 4
data_cfg:
  train_ratio: 0.8
  truncate: 0.05
  resized_image_size: 128
trainer_cfg:
  batch_size: 4
  timesteps: 300
  dim_embeddings: 64
  max_epochs: 64
  checkpoint_interval: 25
  snapshot_path: null
optimizer_cfg:
  weight_decay: 0.1
  learning_rate: 1e-3